name: Node.js CI

on:
  push:
    branches: [ test ]

workflow_dispatch:
  testing:
     runs-on: ubuntu-latest
     env:
        NODE_ENV: test
   steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run tests
        uses: actions/node-test@v2
        with:
          node-version: 12.x
          script:
            - npm test
          env:
             NODE_ENV: test 



      



# jobs:
#     name: Display
#     runs-on: ubuntu-latest
#     env:
#       - NODE_ENV=test
#       - CI=true
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [12.x]
       

#     steps:
#       - uses: actions/checkout@v2
#       - name: Install Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: 12.x
#       - name: Install dependencies
#         run: npm install
#       - name: Run tests
#         run: npm test
#       - name: Display test results




#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v2
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build --if-present
#     - run: npm test